export const todoList = [
  {
    id: 1,
    title: "Học React Props",
    description: "Ôn lại cách truyền dữ liệu từ component cha sang component con.",
    priority: "medium",
    category: "study",
    dueDate: "10/5/2026",
    isCompleted: false,
    createdAt: "2026-05-08T09:00:00.000Z",
  },
  {
    id: 2,
    title: "Làm bài tập Todo List",
    description: "Tạo UI, thêm mới, toggle hoàn thành, xóa và lưu LocalStorage.",
    priority: "high",
    category: "practice",
    dueDate: "12/5/2026",
    isCompleted: false,
    createdAt: "2026-05-08T10:00:00.000Z",
  },
  {
    id: 3,
    title: "Đọc tài liệu useState",
    description: "Hiểu cách React cập nhật state khi người dùng nhập form.",
    priority: "low",
    category: "reading",
    dueDate: "15/5/2026",
    isCompleted: true,
    createdAt: "2026-05-08T11:00:00.000Z",
  },
];
